// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: bank.sql

package repository

import (
	"context"
	"database/sql"
)

const createBank = `-- name: CreateBank :execresult
INSERT INTO bank(
    ` + "`" + `address` + "`" + `,
    ` + "`" + `name` + "`" + `,
    ` + "`" + `countryISO2` + "`" + `,
    ` + "`" + `isHeadquarter` + "`" + `,
    ` + "`" + `swiftCode` + "`" + `
) VALUES (
    ?, ?, ?, ?, ?
)
`

type CreateBankParams struct {
	Address       string `json:"address"`
	BankName      string `json:"bankName"`
	CountryISO2   string `json:"countryISO2"`
	IsHeadquarter bool   `json:"isHeadquarter"`
	SwiftCode     string `json:"swiftCode"`
}

func (q *Queries) CreateBank(ctx context.Context, arg CreateBankParams) (sql.Result, error) {
	return q.exec(ctx, q.createBankStmt, createBank,
		arg.Address,
		arg.BankName,
		arg.CountryISO2,
		arg.IsHeadquarter,
		arg.SwiftCode,
	)
}

const deleteBank = `-- name: DeleteBank :exec
DELETE FROM bank
WHERE SwiftCode = ?
`

func (q *Queries) DeleteBank(ctx context.Context, swiftcode string) error {
	_, err := q.exec(ctx, q.deleteBankStmt, deleteBank, swiftcode)
	return err
}

const getBankBySwiftCode = `-- name: GetBankBySwiftCode :one
SELECT bank.id, bank.name, bank.address, bank.swiftcode, bank.countryiso2, bank.isheadquarter, bank.headquarterid, country.name FROM bank
INNER JOIN country
ON bank.` + "`" + `countryISO2` + "`" + ` = country.` + "`" + `ISO2` + "`" + `
WHERE SwiftCode = ? LIMIT 1
`

type GetBankBySwiftCodeRow struct {
	ID            int32         `json:"id"`
	Name          string        `json:"name"`
	Address       string        `json:"address"`
	Swiftcode     string        `json:"swiftcode"`
	Countryiso2   string        `json:"countryiso2"`
	Isheadquarter bool          `json:"isheadquarter"`
	Headquarterid sql.NullInt32 `json:"headquarterid"`
	Name_2        string        `json:"name_2"`
}

func (q *Queries) GetBankBySwiftCode(ctx context.Context, swiftcode string) (GetBankBySwiftCodeRow, error) {
	row := q.queryRow(ctx, q.getBankBySwiftCodeStmt, getBankBySwiftCode, swiftcode)
	var i GetBankBySwiftCodeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Swiftcode,
		&i.Countryiso2,
		&i.Isheadquarter,
		&i.Headquarterid,
		&i.Name_2,
	)
	return i, err
}

const getBranchesByCountryISO2 = `-- name: GetBranchesByCountryISO2 :many
SELECT id, name, address, swiftcode, countryiso2, isheadquarter, headquarterid FROM bank
WHERE ` + "`" + `countryISO2` + "`" + ` = ? LIMIT ?
`

type GetBranchesByCountryISO2Params struct {
	Countryiso2 string `json:"countryiso2"`
	Limit       int32  `json:"limit"`
}

func (q *Queries) GetBranchesByCountryISO2(ctx context.Context, arg GetBranchesByCountryISO2Params) ([]Bank, error) {
	rows, err := q.query(ctx, q.getBranchesByCountryISO2Stmt, getBranchesByCountryISO2, arg.Countryiso2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bank
	for rows.Next() {
		var i Bank
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Swiftcode,
			&i.Countryiso2,
			&i.Isheadquarter,
			&i.Headquarterid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBranchesByHeadquarterId = `-- name: GetBranchesByHeadquarterId :many
SELECT id, name, address, swiftcode, countryiso2, isheadquarter, headquarterid from bank
WHERE ` + "`" + `headquarterId` + "`" + ` = ? LIMIT ?
`

type GetBranchesByHeadquarterIdParams struct {
	Headquarterid sql.NullInt32 `json:"headquarterid"`
	Limit         int32         `json:"limit"`
}

func (q *Queries) GetBranchesByHeadquarterId(ctx context.Context, arg GetBranchesByHeadquarterIdParams) ([]Bank, error) {
	rows, err := q.query(ctx, q.getBranchesByHeadquarterIdStmt, getBranchesByHeadquarterId, arg.Headquarterid, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bank
	for rows.Next() {
		var i Bank
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Swiftcode,
			&i.Countryiso2,
			&i.Isheadquarter,
			&i.Headquarterid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBranchHeadquarter = `-- name: SetBranchHeadquarter :execresult
UPDATE bank AS branch
INNER JOIN bank AS headquarter
ON LEFT(bank.swiftCode, 8) = LEFT(headquarter.swiftCode, 8)
SET
branch.headquarterId = headquarter.id
WHERE headquarter.isHeadquarter AND branch.id = ?
`

func (q *Queries) SetBranchHeadquarter(ctx context.Context, id int32) (sql.Result, error) {
	return q.exec(ctx, q.setBranchHeadquarterStmt, setBranchHeadquarter, id)
}

const updateBranchesHeadquarter = `-- name: UpdateBranchesHeadquarter :exec
UPDATE bank
SET
` + "`" + `headquarterId` + "`" + ` = ?
WHERE LEFT(` + "`" + `SwiftCode` + "`" + `, 8) = LEFT(?, 8) AND NOT ` + "`" + `isHeadquarter` + "`" + `
`

type UpdateBranchesHeadquarterParams struct {
	HeadquarterId sql.NullInt32 `json:"headquarterId"`
	SwiftCode     string        `json:"swiftCode"`
}

func (q *Queries) UpdateBranchesHeadquarter(ctx context.Context, arg UpdateBranchesHeadquarterParams) error {
	_, err := q.exec(ctx, q.updateBranchesHeadquarterStmt, updateBranchesHeadquarter, arg.HeadquarterId, arg.SwiftCode)
	return err
}
