// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"database/sql"
)

type Bank struct {
	ID            int32         `json:"id"`
	Name          string        `json:"name"`
	Address       string        `json:"address"`
	Swiftcode     string        `json:"swiftcode"`
	Countryiso2   string        `json:"countryiso2"`
	Isheadquarter bool          `json:"isheadquarter"`
	Headquarterid sql.NullInt32 `json:"headquarterid"`
}

type Country struct {
	Iso2 string `json:"iso2"`
	Name string `json:"name"`
}
