services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file: ".env"  
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-puser_password"]
      interval: 5s
      retries: 5
  web:
    env_file: ".env"
    build: .
    ports:
      - "8080:8080"
    depends_on:
      migrate:
        condition: service_completed_successfully
    links:
      - "db:repository"
    restart: always
    networks:
      - backend
  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./repository/migration:/migrations
    command: [
      "-path", "/migrations",
      "-database", "mysql://user:password@tcp(db:3306)/swift_db",
      "up"
    ]
    networks:
      - backend

networks:
  backend:
    driver: bridge