services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file: ".env"  
    networks:
      - backend
  web:
    env_file: ".env"
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - "db:repository"
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge