name: Test in Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t swift-restful-test .

    - name: Run tests
      run: docker run --rm swift-restful-test go test -v ./...

    - name: Clean Up
      run: docker system prune -f